name: Container Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build-server:
    runs-on: ubuntu-latest
    env:
      BUILDAH_FORMAT: oci
    steps:
    - uses: actions/checkout@v2
    - name: Build the server image
      run: make build-server

  build-ad-server:
    runs-on: ubuntu-latest
    env:
      BUILDAH_FORMAT: oci
    steps:
    - uses: actions/checkout@v2
    - name: Build the ad server image
      run: make build-ad-server

  build-client:
    runs-on: ubuntu-latest
    env:
      BUILDAH_FORMAT: oci
    steps:
    - uses: actions/checkout@v2
    - name: Build the client image
      run: make build-client

  test-server:
    #needs: build-server
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test the server image
      run: make test-server

  push:

    # verify it passes build and test first
    needs: test-server

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2
      - name: log in to quay.io
        run: podman login -u "${{ secrets.QUAY_USER }}" -p "${{ secrets.QUAY_PASS }}" quay.io
      - name: push server image
        # note: forcing use of podman here, since we did podman login above
        run: make CONTAINER_CMD=podman push-server
      - name: push ad-server image
        run: make CONTAINER_CMD=podman push-ad-server
      - name: push client image
        # note: forcing use of podman here, since we did podman login above
        run: make CONTAINER_CMD=podman push-client
