apiVersion: v1
kind: Pod
metadata:
  name: sambapod
spec:
  volumes:
    - name: myvol
      persistentVolumeClaim:
        claimName: mypvc
  containers:
    - name: mycontainer
      image: quay.io/obnox/samba-centos8:latest
      ports:
        - containerPort: 139
          name: "samba139"
        - containerPort: 445
          name: "samba445"
      volumeMounts:
        - mountPath: "/share"
          name: myvol

